version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - http.host=0.0.0.0
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - infrastructure
      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.10
    ports:
      - "5601:5601"
    networks:
      - infrastructure
    depends_on:
      - elasticsearch
volumes:
    esdata:
        driver: local
networks:
    infrastructure:
        driver: bridge